
#define SCREEN_WIDTH   1280
#define SCREEN_HEIGHT  720
#define MAX_ENTITIES_LIMIT 5000
#define MAX_COMPONENTS_LIMIT 32
#define OFFSCREEN_SPAWN_BUFFER 50
#define OFFSCREEN_DEAD_ZONE 100;

//Player defs
#define PLAYER_SPEED 3
#define PLAYER_SIZE 50
#define PLAYER_PROJECTILE_SPEED 10

// Asteroid Defs
#define MAX_ASTEROIDS 10
#define ASTEROID_VELOCITY 3
#define MIN_ASTEROID_WIDTH 10
#define MAX_ASTEROID_WIDTH 50
#define MIN_ASTEROID_HEIGHT 10
#define MAX_ASTEROID_HEIGHT 50
#define ASTEROID_VERTICES 9

